language: ruby
rvm:
  - 2.2.2
install:
  - bundle update
  - bundle install
  - bundle exec jekyll build

script: true

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
